### ISSUE TITLE
Remove config bootstrap code from examples

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#111]
Currently the examples use the ExampleConfigCreator class to bootstrap the process of creating their initial configuration. This should be loaded from a genuine configuration service. Once we have a backing store that can persist data e.g. etcd or properties, then the examples should be moved over to use this method.

1. Create a example properties file, one for single JVM, one for multi JVM.
2. Initialise the configuration service to pull from a backing store that uses these files.
3. Change examples to request data from this genuine configuration service.
4. Remove ExampleConfigCreator.

**Comment by ac74475** [comment]
merged into develop
