### ISSUE TITLE
Prevent Services being re-instantiated with every REST call

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#124]
The various services are currently being re-created with every single REST call that is received. This should not happen. When they have been first instantiated they should stay created and be re-used.

For example when the multi-jvm-example-rest-palisadeservice is started, every call to the REST service creates a new instance of SimplePalisadeService.

I believe this is a bug in the REST server somewhere.

**Comment by ac74475** [comment]
merged into develop
