### ISSUE TITLE
Allow lambda's in Rules

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#130]
At the moment there are several ways to define rules, however they all require that the Rule/Function/Predicate is a pre-compiled Java class which is distributed with the data service at the time of deployment. It would be really valuable if we could find a way to allow lambda functions to be used within those Rule's, in a way that doesn't need the data service to be redeployed when a new rule is generated.

**Comment by m09526** [comment]
Will become part of wider work on how policy in Palisade is defined.
