### ISSUE TITLE
Fix for issue gh-152 breaks module management

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#158]
The changes to remove the example models from building under mvn profiles has caused IdeaJ module management to disregard all Java code under "example". This means that classes can't be found and also means that refactorings no longer make changes as necessary to these classes.

**Comment by m09526** [comment]
It also prevents the example/multi-jvm-example/scripts/start*service.sh scripts from working.

**Comment by ac74475** [comment]
This just requires each of the example/multi-jvm-example/scripts/start*service.sh scripts to remove the quick profile from the mvn clean install command

**Comment by ac74475** [comment]
merged into develop
