### ISSUE TITLE
Create rules ready to integrate HR data into the example model

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#183]
We need to integrate the HR data that we can now generate, to build up a realistic GDPR based example that can run offline at small scale based on 100-200 records, but also can run on a cloud cluster platform on 10-100 million records per file.

To do this I would expect the need to have several 'allowed uses' to signify that the data is allowed to be used for the given purpose. I am currently thinking these would be 'Duty of Care', 'Tax', 'Salary' and 'staff report'.

I would then expect there to be a number of roles such as 'HR', 'Payroll' and 'Estates'.

This would enable us to have policies such as:
- the employee contact details can only be seen by HR or the employees manager for the purpose of 'Duty of Care'. This prevents those sensitive details being exposed unnecessarily.
- The nationality can only be seen by HR for the purpose of 'Staff report', which allows for diversity transparency reports to be generated without exposing sensitive data that is not required for any other purpose.
- A person in Estates can only see an employee's address post code with the last character removed to reduce the precision. This would allow estates to know roughly where their employees live to enable better transport link planning, without exposing sensitive data.
- An employees bank details are only available to 'Payroll' for the purpose of 'Salary'

**Comment by r34721** [comment]
Merged into develop branch
