### ISSUE TITLE
Update Jackson JSON library

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#194]
The Jackson library version in Palisade is 2.6.5 and is out of date with respect to new versions of Java. Specifically the jsr310 library is no longer required. Also, some of the calls being used in the JSONSerialiser class are deprecated and some of the annotations were being pulled in via transitive dependencies. Since we have now listed these dependencies explicitly, IdeaJ was complaining that it wanted a newer version for the jackson-annotations module. To avoid having conflicting versions, I suggest we upgrade the whole module.

**Comment by ac74475** [comment]
merged into develop
