### ISSUE TITLE
Cache service enhancements

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#213]
This is to add some enhanced behaviour to the cache service to make it more widely useful in Palisade.

 - Add a remove method to allow key/values to explicitly removed rather than waiting for a time to live to expire (if one was set)
 - Add a "locally cacheable" flag to AddCacheRequest. SimpleCacheService then stores these k/vs locally when retrieved for a short period of time knowing they can go stale, but this is accepted by the client. This is to prevent requests for the same key repeatedly going to the backing store.
 - Add a facility to allow services to "register" their up-state with the cache service. This forms the basis of a heartbeat mechanism so services can find which service instances are present. The proposed form is for a service to register a very short (few seconds) key with the cache service. This key contains the service type as normal, plus the address for the service instance. The list of all service instances of type X can then be retrieved by submitting a "list" request for the needed prefix. New methods would be provided in cache service to facilitate this.

**Comment by ac74475** [comment]
merged into develop
