### ISSUE TITLE
Integrate HR dataset and rules into the examples

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#260]
Instead of using a 8 line text file for the example data source we want to make use of the Employee HR data that we now have a generator for and some rule for. See gh-183 and gh-102. For the locally run examples we should use a single file of 100 employees. For the cloud deployed examples it would be good to generate 10 files of 1 million employees to run the example against.

I would want to use the 4 scenarios that are mentioned in gh-183. E.g. Alice is in 'HR' and 'Payroll', Bob is in Estates.
- Alice queries the employee dataset for the purpose of "Salary" and therefore should be able to see employee's bank details, but not see their contact information or nationality.
- Alice queries the employee dataset for the purpose of duty of care and therefore should see all the contact information but no bank details or nationality.
- Alice queries the employee dataset for the purpose of "Transparency Report" and should get the employees nationality but not their contact or bank details.
- Bob queries the employee dataset with the purpose of duty of care and should only see the contact details of those he is in the management chain of and not bank details or nationality.
- Bob queries the employee dataset with no defined purpose and get the address details masked to reduce precision and no nationality, contact details or bank details.

**Comment by developer6959** [comment]
Roles and justifications/purposes are all in UPPERCASE:
Roles:
HR
PAYROLL
ESTATES

Purpose/Justification:
SALARY
DUTY_OF_CARE
STAFF_REPORT (not Transparency Report)

**Comment by developer6959** [comment]
Closed in error

**Comment by developer6959** [comment]
Pull Request created - ready for review

**Comment by ac74475** [comment]
merged into develop
