### ISSUE TITLE
Config request should include class name not object

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#266]
When the Get/Add config request is posted to the configuration manager, it includes and Optional Class instance which the configuration manager uses to fetch/set the config. Unfortunately, this requires the configuration manager to have access to that class, even though it never actually does anything with them. This requires the config manager to then have a dependency on the JAR that contains this class. This could lead to bloat in the config. manager micro-service. It is unnecessary since all it needs is the name of the class to set/retrieve. Update the backend API so that only that name of the class is sent across to the configuration manager.

**Comment by ac74475** [comment]
merged into develop
