### ISSUE TITLE
Request implementation classes don't call super in equals/hashcode 

### ISSUE THREAD

**Issue by p013570** [gchq/Palisade#27]
We need to update the equals and hashcode methods for the Request implementations so they call super.equals and super.hashcode.

These methods can be auto generated using intelij.

In order to be able to pass the Request objects around as JSON we would need the id to be able to be set from JSON. Currently you cannot manually set the value. We should remove the 'final' keyword and add a setter.

**Comment by m55624** [comment]
Merged into develop.
