### ISSUE TITLE
Allow ProxyRest clients to catch NoCapacityExceptions from DataService

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#277]
When a DataService sends the "I'm too busy" exception back to a client, the client should catch this exception explicitly as opposed to a general failure exception and retry contacting the redirector. It should not be interpreted as a communication failure. The purpose of this is to allow a zero configuration/negotiation method for a data service to hand off a client to another instance without needing any communication between data services, or between data service and redirector. Thus when a large job starts and an external orchestration service starts up new data services in response, if the client(s) request data before new instances start up the existing data service instances can keep sending them back to the redirector until the new ones start up.

**Comment by ac74475** [comment]
merged into develop
