### ISSUE TITLE
Rename the resource DataType attribute to DataSchema?

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#29]
It has been highlighted that having a dataType attribute on the resource which is specifying what the java object is that the data will be serialised to. Can be confused as actually meaning the type of the file, such as Avro or CSV.

Therefore we could rename it to dataSchema instead as the Java object is representing the structure of the data.

**Comment by GCHQDeveloper404** [comment]
> Can be confused as actually meaning the type of the file, such as Avro or CSV.
Yep I just failed that test.

**Comment by ac74475** [comment]
refactoring done in issue 32
