### ISSUE TITLE
Investigate why the swagger doc, in all microservices shows the DataService "read" calls

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#307]
Visiting a microservice end point with a browser shows the Swagger generated pages. For some reason they all seem to include the DataService "read" calls at the moment. This obviously shouldn't be here. Any attempt to use them on other services generates a HTTP 404 error correctly.

**Comment by m09526** [comment]
The Policy end-point has both POST and PUT on /, is this correct? It doesn't appear to be so from the REST spec.
All services seem to expose the DataService read calls.

**Comment by m09526** [comment]
Policy service is correct.
DataService being exposed due to dependency in example-model module.

**Comment by ac74475** [comment]
merged into develop
