### ISSUE TITLE
Pull out hr data generator into a separate repo

### ISSUE THREAD

**Issue by nw1984** [gchq/Palisade#324]
The hr data generator is a separate executable - pull out this functionality into a separate repo.

**Comment by ac74475** [comment]
This should be extracted out as its own repo and then split into two modules (Employee types and data generator). That way any projects wanting to use the data created can just import the Employee types jar and not the who data generation code.

**Comment by m09526** [comment]
Given the size of the code, I think we could keep this as one module.
