### ISSUE TITLE
Fix intermittent test failures in HierarchicalPolicyServiceTest

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#345]
I have so far hit issues with ln 177 and ln 205 in the HierarchicalPolicyServiceTest

**Comment by m09526** [comment]
Line numbers updated to reflect changes: 180 , 208 (line reads assertEquals(....)

**Comment by m09526** [comment]
Unable to reproduce

**Comment by ac74475** [comment]
I only seem to be able to reproduce the error within an Azure pipeline build on the gh-163-azure-aks branch

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running uk.gov.gchq.palisade.policy.service.impl.HierarchicalPolicyServiceTest
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.836 s <<< FAILURE! - in uk.gov.gchq.palisade.policy.service.impl.HierarchicalPolicyServiceTest
[ERROR] getApplicableRecordLevelRules(uk.gov.gchq.palisade.policy.service.impl.HierarchicalPolicyServiceTest)  Time elapsed: 0.014 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Does nothing[, Check user has 'Sensitive' auth]> but was:<Does nothing[]>
	at uk.gov.gchq.palisade.policy.service.impl.HierarchicalPolicyServiceTest.getApplicableRecordLevelRules(HierarchicalPolicyServiceTest.java:120)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   HierarchicalPolicyServiceTest.getApplicableRecordLevelRules:120 expected:<Does nothing[, Check user has 'Sensitive' auth]> but was:<Does nothing[]>
[INFO] 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
