### ISSUE TITLE
Ensure cat client uses correct class pending gh-331

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#360]
Once gh-331 and gh-73 are resolved, then there is likely some remedial work to ensure the cat client uses the updated classes for client configuration. Namely, RestUtil has moved, the creation of the ServiceState object now has a more sensible implementation and has been moved to a different package.

**Comment by ac74475** [comment]
Cat client is using the right classes but does need updating to use originalRequestId's on the requests following the merge of gh-293 and gh-294
