### ISSUE TITLE
Clients need the data schema

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#362]
The Palisade clients need to know the schema of the data if they are to deserialise the data. 

My current thinking is for the schema information to be supplied by the resource service and therefore passed back to the clients in the resource metadata that is in the mapping of resource -> data service connection details.

**Comment by nw1984** [comment]
General opinion is that trying to make Palisade clients know the data schema is not a very good idea.
The schema is not specifically defined in the data service - at the moment the object being retrieved and the serialiser define the schema - for instance Employee objects are serialised by Avro. This feels like a wider question that we need to discuss as a team.
I'm moving this back to ToDo after the off site discussions of Monday 10th June through Wednesday 12th June. The priority being at the moment that we concentrate on the high side MVP1.
