### ISSUE TITLE
CONFIG_SERVICE_PATH should not contain dots

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#364]
Given the idea of the CONFIG_SERVICE_PATH variable is that it is a system environment variable. In linux the system environment variables cannot contain dots. Therefore having the default CONFIG_SERVICE_PATH="palisade.rest.config.path" does not work. we should replace the dots with underscores so CONFIG_SERVICE_PATH="palisade_rest_config_path"

**Comment by m09526** [comment]
It's a Java System property not an environment variable. It needs to be specified to the VM using the -D switch on the command line. Setting and environment variable won't be picked up.

**Comment by ac74475** [comment]
There are two issues with that. Firstly if we have clients in different programming languages, we still want them all to run from the same config service per system. Secondly there is the extra complexity of when you have a test and a prod environment you don't want to go and change every script to update this variable, instead you just want a single system variable to be changed and all services to run off that.
Therefore I think this ticket needs to update this to be a system level environment variable rather than a Java System property

**Comment by ac74475** [comment]
merged into develop
