### ISSUE TITLE
Need to be able to support deployments using their own User and Context objects

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#371]
Currently if we try to use an ExampleUser object in the example which extends User it fails due to json serialisation issues, see https://github.com/gchq/Palisade/commit/04801ea1d25278e2286fe9f988378b59ebb3a798 for an example of what we want to be able to do.

**Comment by m09526** [comment]
Are there any other domain objects that are likely affected by the same issue? I couldn't see any on a quick look through the 'common' module.

**Comment by m09526** [comment]
I'm upgrading this to critical because it is likely to enable a lot more usecases for Palisade when it's done.

**Comment by ac74475** [comment]
merged into develop
