### ISSUE TITLE
Need a better error message when no environment variable set

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#387]
Currently a NullPointerException is thrown from  StreamUtil.openStream(SetPolicyAction.class, System.getProperty(ConfigUtils.CONFIG_SERVICE_PATH)); in various code files when the System property (or env. variable in later versions) is not set. This should be replaced by an informative error message asking that the environment variable be set correctly.

**Comment by m09526** [comment]
This should also look at the error (or lack thereof) produced when the RestConfigService can't find it's system property/environment variable.

**Comment by ac74475** [comment]
merged into develop
