### ISSUE TITLE
Add builder methods on the common objects

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#4]

**Comment by p013570** [comment]
We have already added a few to the User class. Essentially just add some methods in the form:


```java
public class Pojo {
    private String x;
    private String y;

    public Pojo x(final String x) {
        this.x = x;
        return this;
    }

    public Pojo y(final String y) {
        this.y = y;
        return this;
    }
}
```

The Pojo class can then be initialised like:
```java
Pojo pojo = new Pojo().x("value of x").y("value of y");
```

For classes with lots of fields this will make it clearer than have lots of different constructors with different combinations of parameters. We should then be able to remove all of the constructors from the class. This approach could be applied to the majority of our simple classes like the Request classes.

**Comment by p013570** [comment]
Merged into develop.
