### ISSUE TITLE
Create an example that runs on AWS EC2 and accesses data in an S3 bucket

### ISSUE THREAD

**Issue by developer6959** [gchq/Palisade#417]
To run natively on AWS EC2 Palisade should make use of IAM to allow/deny access to data in an S3 bucket. Create an example that uses Terraform to 
1. Create an S3 bucket and populate it with example data.
2. Spin up an EC2 instance.
3. Create and grant an IAM role to the instance to allow it to access the example data in the S3 bucket.
4. Demonstrate the instance successfully reading the data and Palisade applying rules.
5. Demonstrate another instance without the role being unable to access the data.

**Comment by m09526** [comment]
Couple of modifications for the above:
There should be two EC2 instances, one with the IAM role and one without. Start all the Palisade services on the instance with the IAM role. Then on the instance without the IAM role, demonstrate that accessing the S3 bucket directly fails. Then demonstrate that it can be accessed via Palisade.

To make this work, you will need to uncomment the Hadoop-aws dependency in hadoop-resource-service and hadoop-data-service. The Hadoop data service will also need some configuration to ensure it knows to use the S3 file system by default. This can be configured when configure-services runs by setting the environment varialbe HADOOP_CONF_PATH to point at extra config files. The template you will need to adapt is in example/resource/hadoop_minio_s3.xml. Copy and update this to point at actual S3 (with appropriate bucket name). As long as Configure-services launches with HADOOP_CONF_PATH environment variable set, then the resource and data service should be configured to read from S3.

When passing files names to the Examples, pass s3 paths as s3a://bucket-name/blah.

**Comment by ac74475** [comment]
merged into develop
