### ISSUE TITLE
Add null check on all the various builder methods around the codebase

### ISSUE THREAD

**Issue by m09526** [gchq/Palisade#43]
Many of the builder methods take objects of the form:

```
public DataRequestResponse resource(final Resource resource, final ConnectionDetail connectionDetail) {
        resources.put(resource, connectionDetail);
        return this;
}
```

Without the appropriate "`Objects.requiresNonNull(....)`" checks in place, we are allowing null values to be injected into objects. This can cause issues later in the runtime when a unrelated method suddenly finds a null object or map where it is not expecting/cannot handle one.

The following classes need modification (derived from "develop" branch):

UserId
User
Context
RequestID
Justification
SimpleConnectionDetail
Request
DataRequestResponse
DataRequestConfig
AbstractResource
System/Stream/File/DirectoryResource
Rules
AuditRequest
AddCacheRequest
GetCacheRequest
ReadRequest
ReadResponse
DataReaderRequest
DataReaderResponse
RegisterDataRequest
MultiPolicy
Policy
CanAccessRequest
GetPolicyRequest
SetPolicyRequest
AddResourceRequest
GetResourcesBy*Request
AddUserRequest
GetUserRequest

Null checks should be of the form for an argument named "dataItem"
`Objects.requireNonNull(dataItem, "dataItem");`

For arrays, e.g. public User auths(final String... auths) the following should be used:
```
Objects.requireNonNull(auths,"auths");
for (final String auth : auths) {
    if (auth == null) {
        throw new NullPointerException("entry in auths");
    }
}
```
For situations where a String is initialised to null by the constructor, a sentinel "UNKNOWN" value should be used. For example of how to do this, please see UserId or RequestId classes.

**Comment by GCHQDeveloper404** [comment]
I have some questions about this ticket, with the example below.

```
public class AuditRequest extends Request {
    private Justification justification;  //(will be replaced with the Context class, but ignore that for now)
    private User user;
    private Resource resource;
    private String howItWasProcessed;
    private Exception exception;
```

For null not to exist then theses field will need to be initialised with "Empty" instances of classes.
i.e. Justification will require a new instance with a "NOT SET" value for the string. And Resource will require EmptyResource.

At scale could occupy and take up lots of memory. Is this the approach you want?
In my current PR (not perfect) I have null checks to avoid adding null keys to maps, which could be damaging.

```
public Rules<T> simpleFunctionRule(final String id, final Function<T, T> rule) {
         Objects.requireNonNull(id);
         Objects.requireNonNull(rule);
         rules.put(id, new WrappedRule<>(rule));
         return this;
     }
```

but I also have null checks, similar to below, which could be replaced with "IF IGNORE" instead of throwing errors.

```
public Rules<T> rules(final LinkedHashMap<String, Rule<T>> rules) {
         Objects.requireNonNull(rules);
         this.rules.putAll(rules);
         return this;
     }
```

Are you not wanting ways to delete/reset values within the classes?

THINKING ALOUD
Could null fields exist and the getter is responsible for returning a "null instance" or default value?
All Class reference to fields within class must for through the safe getter?

thoughts?

**Comment by m09526** [comment]
Sorry for taking a while to get back on to this issue.

I've added Context to the class list above that needs modification.

I'm not keen on the idea that getter methods are responsible for the internal consistency of a class. Getter methods should follow standard idioms. Class consistency should be maintained at the point of mutation, not cleaned up afterwards.

I like the idea of having default values, as has been done already in UserId. The User class can then use a default constructed UserId as it's default value for its userId field.

On the point of memory usage, this shouldn't become and issue as most of the "default" values can be private static inside the class. Thus there is only ever one instance of them in memory.

In the rules method example shown above, there should be a `this.rules.clear()` call in there before `putAll()` is called. Thus, reseting that particular class is just a case of calling `rules()` with an empty map.

**Comment by ac74475** [comment]
Due to the potential for the previous proposal being a nightmare to debug, we have decided the following:
- all mutator methods will have Object.requireNonNull() checks with helpful messages.
- all getter methods will have Object.requireNonNull() checks with helpful messages unless the getter is used repeatedly and would therefore excessively hamper performance.
- all setter methods that also have a builder method, will be a wrapper around the builder method.
- all variables will be initialised null unless required to be otherwise.

**Comment by ac74475** [comment]
The style of the class should look like this:
```java
/**
 * A {@link UserId} uniquely identifies a {@link User}.
 */
public class UserId implements Cloneable {

    public static final String NAMESPACE = "UserId";
    public static final String ID = "id";

    private static final Map<String, FieldGetter<UserId>> FIELD_GETTERS = createFieldGetters();
    private static final Map<String, FieldSetter<UserId>> FIELD_SETTERS = createFieldSetters();

    private String id;

    /**
     * Constructs an empty {@link UserId}.
     */
    public UserId() {
    }

    /**
     * Updates the id of the UserID
     *
     * @param id a non null String representing the id of the user
     * @return the UserId object
     */
    public UserId id(final String id) {
        Objects.requireNonNull(id, "The UserId id field can not be set null.");
        this.id = id;
        return this;
    }

    public void setId(final String id) {
        id(id);
    }

    public String getId() {
        Objects.requireNonNull(id, "The UserId id field has not been initialised.");
        return id;
    }

    /**
     * Adds a key value pair to a map which can then be used within the policy rules to make policy decisions.
     *
     * @param reference the key that references the value in the map
     * @param value the object that you want to store in the map
     * @return the UserId object
     */
    public UserId field(final String reference, final Object value) {
        Objects.requireNonNull(reference, "The reference parameter cannot be null.");
        Objects.requireNonNull(value, "The value parameter cannot be null.");
        Util.setField(this, FIELD_SETTERS, reference, value);
        return this;
    }

    public void setField(final String reference, final Object value) {
        field(reference, value);
    }

    public Object getField(final String reference) {
        Object field = Util.getField(this, FIELD_GETTERS, reference);
        Objects.requireNonNull(field, "The field for " + reference + " is not set.");
        return field;
    }

    public UserId clone() {
        UserId clone;
        try {
            clone = (UserId) super.clone();
        } catch (final CloneNotSupportedException e) {
            clone = new UserId();
        }
        clone.id = id;
        return clone;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final UserId userId = (UserId) o;

        return new EqualsBuilder()
                .append(id, userId.id)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(7, 37)
                .append(id)
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("id", id)
                .toString();
    }

    private static Map<String, FieldGetter<UserId>> createFieldGetters() {
        Map<String, FieldGetter<UserId>> map = new HashMap<>();
        map.put(ID, (userId, subfield) -> userId.getId());
        return Collections.unmodifiableMap(map);
    }

    private static Map<String, FieldSetter<UserId>> createFieldSetters() {
        Map<String, FieldSetter<UserId>> map = new HashMap<>();
        map.put(ID, (userId, subfield, value) -> userId.setId(((String) value)));
        return Collections.unmodifiableMap(map);
    }
}
```

**Comment by ac74475** [comment]
merged into develop
