### ISSUE TITLE
Create a HDFS resource service

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#6]
Create a resource service that uses the HDFS API to find out what resources exist and to return the list of resources. 
The connection details should be in the form of ```'hdfs://<path to resource>'```. 
The format should be the file ending, e.g (filename bob_00001.txt would have format of 'txt'. 
The type should be the first word in the resource name, e.g (filename bob_00001.txt would have type of 'bob'. 
The id should be the same as the connection details.

**Comment by GCHQDeveloper404** [comment]
@ac74475 
> getResourcesById
Is the expected behaviour to get all files from a path which match "0001".
or is the expected behaviour that the ID is the path/folder and to return all files.
